### ISSUE TITLE
How to change the default subdirectory and point to the correct subdirectory? 

### ISSUE THREAD

**Issue by Hperea** [modflowpy/flopy#1110]
m = flopy.modflow.Modflow.load(nam,model_ws=GW_path,verbose=False,
                               check=False,exe_name=MF_exe, load_only=(pckgs))
Traceback (most recent call last):

  File "<ipython-input-1-afb89df546e5>", line 14, in <module>
    m = flopy.modflow.Modflow.load(nam,model_ws=GW_path,verbose=False,

  File "C:\Users\hperea\Anaconda3\envs\py385\lib\site-packages\flopy\modflow\mf.py", line 762, in load
    ext_unit_dict = mfreadnam.parsenamefile(

  File "C:\Users\hperea\Anaconda3\envs\py385\lib\site-packages\flopy\utils\mfreadnam.py", line 177, in parsenamefile
    fls = os.listdir(dn)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Work\\Y2021\\19-1134\\hvwp_20210505a_bpa2\\HVWP_rch_5lyrs\\Work\\Y2021\\19-1134\\hvwp_20210505a_bpa2\\HVWP_rch_5lyrs'

**Comment by jdhughes-usgs** [comment]
If the name file is in the `GW_path` directory you do not need the path on `nam`.

Reopen the issue if this does not solve the problem. If you reopen the issue please provide more information.
