### ISSUE TITLE
PlotCrossSection on MF6 DISU grid with line={'Column': 5}

### ISSUE THREAD

**Issue by javgs-bd** [modflowpy/flopy#1130]
I'm trying to make PlotCrossSection work on a MF6 DISU model. I'm testing with a working example which is an extract of **flopy3_gridgen.ipynb**  and then I'm trying to follow the example in **flopy3.3_PlotCrossSection.ipynb** for vertex grids. 

The code of the example model is shown below (the only difference with the notebook is that I'm placing the gridgen executable inside the model_ws structure folder).
PlotCrossSection works if the line is defined via coordinates (commented line below) but if a column or row number is passed, I get the following error. I wonder if that is correct, as the concept of a xsect through a column or row might be ambiguous unless it means it goes exactly through the middle of the parent cell in that column/row.

```
Traceback (most recent call last):

  File "C:\Users.....\Basic.py", line 101, in <module>
    xsect = flopy.plot.PlotCrossSection(model=gwf, line={'Column': 5})

  File "C:\Users\.....\.conda\envs\flopy-develop\lib\site-packages\flopy\plot\crosssection.py", line 132, in __init__
    xedge, yedge = self.mg.xyedges

AttributeError: 'UnstructuredGrid' object has no attribute 'xyedges'
```

Code

```
import os
import sys
import shutil
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

from shapely.geometry import Polygon

try:
    import flopy
except:
    fpth = os.path.abspath(os.path.join('..', '..'))
    sys.path.append(fpth)
    import flopy

from flopy.utils.gridgen import Gridgen 

gridgen_ws = './gridgen'

if not os.path.exists(gridgen_ws):
    os.makedirs(gridgen_ws)

model_ws = os.path.join('.', 'data')

if not os.path.exists(model_ws):
    os.makedirs(model_ws)
    

from shapely.geometry import Polygon
name = 'dummy'
nlay = 3
nrow = 10
ncol = 10
delr = delc = 1.
top = 1
bot = 0
dz = (top - bot) / nlay
botm = [top - k * dz for k in range(1, nlay + 1)]

sim = flopy.mf6.MFSimulation(sim_name=name, sim_ws=gridgen_ws, exe_name='mf6')
gwf = flopy.mf6.ModflowGwf(sim, modelname=name)

dis = flopy.mf6.ModflowGwfdis(gwf, nlay=nlay, nrow=nrow, ncol=ncol, 
                              delr=delr, delc=delc,
                              top=top, botm=botm)

g = Gridgen(dis, model_ws=gridgen_ws)
polys = [Polygon([(4, 4), (6, 4), (6, 6), (4, 6)])]
g.add_refinement_features(polys, 'polygon', 3, layers=[0])
g.build()

disu_gridprops = g.get_gridprops_disu6()
disu_gridprops.keys()

gridprops_ug = g.get_gridprops_unstructuredgrid()
ugrid = flopy.discretization.UnstructuredGrid(**gridprops_ug)

f = plt.figure(figsize=(10, 10))
for ilay in range(g.nlay):
    ax = plt.subplot(1, g.nlay, ilay + 1)
    ugrid.plot(layer=ilay, ax=ax)

gwf = flopy.mf6.ModflowGwf(sim, modelname=name, save_flows=True)
disu = flopy.mf6.ModflowGwfdisu(gwf, **disu_gridprops)

line = np.array([(4.1, -0.1), (4.1, 10.1)])


f = plt.figure(figsize=(10, 10))
for ilay in range(gwf.modelgrid.nlay):
    ax = plt.subplot(1, g.nlay, ilay + 1)
    ax.set_aspect('equal')
    pmv = flopy.plot.PlotMapView(gwf, layer=ilay, ax=ax)
    pmv.plot_grid(colors='k', alpha=0.1)
    plt.plot(line.T[0], line.T[1], 'r--', lw=1)


f = plt.figure(figsize=(10, 10))
ax = f.add_subplot(1, 1, 1)
xsect = flopy.plot.PlotCrossSection(model=gwf, line={'Column': 5})
#xsect = flopy.plot.PlotCrossSection(model=gwf, line={'line': line})
line_collection = xsect.plot_grid()
```

**Comment by jlarsen-usgs** [comment]
@javgs-bd 

Because vertex and unstructured grids are defined by coordinate locations and cells can be any combination of shapes the 'row' and 'column' designation is ambiguous and are not defined in MODFLOW. The solution to this is to pass coordinate information into `PlotCrossSection` using `line={'line': [[x0, y0], [x1, y1]]}`.

**Comment by javgs-bd** [comment]
@jlarsen-usgs my apologies. I guess I got confused by the code using the 'column' argument in in the flopy3.3_PlotCrossSection.ipynb notebook before vertex grids are dealt with (In [21]). I see now that code applies to a regular MF6 grid.
