### ISSUE TITLE
Cannot open subsidence.hds generated from the SUB package

### ISSUE THREAD

**Issue by Boorn123** [modflowpy/flopy#1259]
I created a model based on Modflow 2005. The SUB package has been added. I tried to open the subsidence.hds file generated from the model that shows a normal termination of simulation.
```
fname = os.path.join(modelpath, 'model1.subsidence.hds')
hds = bf.HeadFile(fname)
```
However, an error occurred as follows.
```
Traceback (most recent call last):
  File "<ipython-input-5-a5d60c702951>", line 2, in <module>
    hds = bf.HeadFile(fname)
  File "C:\Users\Boorn\anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 495, in __init__
    super(HeadFile, self).__init__(filename, precision, verbose, kwargs)
  File "C:\Users\Boorn\anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 283, in __init__
    super(BinaryLayerFile, self).__init__(
  File "C:\Users\Boorn\anaconda3\lib\site-packages\flopy\utils\datafile.py", line 202, in __init__
    self._build_index()
  File "C:\Users\Boorn\anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 314, in _build_index
    header = self._get_header()
  File "C:\Users\Boorn\anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 369, in _get_header
    return header[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
All the input and output files as well as the script have been attached. Any responses and help will be very much appreciated.
[Model.zip](https://github.com/modflowpy/flopy/files/7295158/Model.zip)

**Comment by mwtoews** [comment]
The error message is not really helpful, but try `flopy.utils.HeadFile(fname, text="subsidence")` to read other data files.
