### ISSUE TITLE
Unable to load mf6 model with an ATS package

### ISSUE THREAD

**Issue by hjia1005** [modflowpy/flopy#1426]
Hi,
I created a model with ATS package, then I am trying to load the model but failed. It always worked without the ATS package.
What is the reason for it? I copied all the error messages below for you to check.

sim = flopy.mf6.MFSimulation.load(sim_name='mfsim', 
                                      version='mf6', 
                                      exe_name='../bin/mf6_3.exe', 
                                      sim_ws='../test_ats')
loading simulation...
  loading simulation name file...
  loading tdis package...
Traceback (most recent call last):

  File "C:\Users\xxxxx\AppData\Local\Temp/ipykernel_29320/3789005127.py", line 1, in <module>
    sim = flopy.mf6.MFSimulation.load(sim_name='mfsim',

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\modflow\mfsimulation.py", line 689, in load
    instance._tdis_file.load(strict)

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 2437, in load
    self._load_blocks(fd_input_file, strict)

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 2614, in _load_blocks
    cur_block.load(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 994, in load
    key, result = self._find_data_by_keyword(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 1059, in _find_data_by_keyword
    pkg = self._model_or_sim.load_package(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\modflow\mfsimulation.py", line 1030, in load_package
    package = package_obj(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\modflow\mfutlats.py", line 170, in __init__
    self.maxats = self.build_mfdata("maxats", maxats)

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 2320, in build_mfdata
    ds = self.blocks[block.name].add_dataset(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 584, in add_dataset
    self.datasets[var_path[-1]] = self.data_factory(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\mfpackage.py", line 424, in data_factory
    return mfdatascalar.MFScalar(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\data\mfdatascalar.py", line 54, in __init__
    self._data_storage = self._new_storage()

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\data\mfdatascalar.py", line 649, in _new_storage
    return DataStorage(

  File "C:\DDrive\anaconda\lib\site-packages\flopy\mf6\data\mfdatastorage.py", line 323, in __init__
    and package_dim.model_dim[0].model_name.lower()

AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by spaulins-usgs** [comment]
@hjia1005, please download and use the latest version of flopy from the develop branch.  Flopy had a number of compatibility problems with the new ATS package that were fixed last month.

**Comment by hjia1005** [comment]
@spaulins-usgs thanks for your reply.
Just downloaded it using - pip install https://github.com/modflowpy/flopy/zipball/develop
Got the same error. Have to deactivate ATS for now.

**Comment by cnicol-gwlogic** [comment]
@hjia1005 - try pip install https://github.com/modflowpy/flopy/zipball/develop --upgrade --force-reinstall

**Comment by hjia1005** [comment]
@cnicol-gwlogic 
Had a permission issue, then added --user to the end of the command, finally worked. Thank you very much!

**Comment by hjia1005** [comment]
Closed.
