### ISSUE TITLE
bug: CellBudgetFile throws error reading binary cbb  (output from modflow6)

### ISSUE THREAD

**Issue by SamanTavakoli** [modflowpy/flopy#1572]
flopy throws the following error attemping to read .cbb (output from **modflow6**) file which apears to be related to nbytes count. 
****
Traceback (most recent call last):

    cbb = flopy.utils.binaryfile.CellBudgetFile(fname, precision = 'auto')

    File "C:\ProgramData\Anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 667, in __init__
     success = self._set_precision("single")

    File "C:\ProgramData\Anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 765, in _set_precision
     self._build_index()

    File "C:\ProgramData\Anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 904, in _build_index
     self._skip_record(header)

    File "C:\ProgramData\Anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 971, in _skip_record
     self.file.seek(nbytes, 1)

    OSError: [Errno 22] Invalid argument

**Comment by langevin-usgs** [comment]
what if you set precision="double"?

**Comment by SamanTavakoli** [comment]
Thank you. It worked!

**Comment by w-bonelli** [comment]
I haven't been able to reproduce this with a `.cbb` file generated by `tutorial01_mf6` &mdash; using `precision="auto"` works OK. @SamanTavakoli if you could provide more code and/or your cell budget file it could help determine why you're seeing this.

`CellBudgetFile` keeps a file handle open and moves/resets it in the routine that automatically determines precision. The `OSError` suggests the `seek(nbytes, 1)` call in `_skip_record()` specified an invalid relative position &mdash; some combination of `seek` calls seems to have moved the handle somewhere unexpected.

**Comment by jlarsen-usgs** [comment]
@w-bonelli 

We've seen this issue crop up before, where the "auto" routine fails to identify the correct file precision, in a few select cases. I can remember all of the details, but I do remember that it is a challenging problem. If you investigate this, I'd recommend looking at the `CellBudgetFile._set_precision()` routine.
