### ISSUE TITLE
Can set_data infer "layer(s)" by shape of array?

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#1698]
**Describe the bug**
Clarification, it seems to only be idomain.set_data() method that no longer infers the number of layers, passing "layer" appears to be required.

**To Reproduce**
1. `a = np.ones((nlay,nrow,ncol)).astype(int)` or `a = np.stack([np.ones((nrow,ncol))]*nlay, axis=0).astype(int)`
2. `gwf.dis.idomain.set_data(a)` or `gwf.dis.idomain.set_data(a, layer=range(0,model['nlay']))` or `gwf.dis.idomain.set_data(a, layer=[_ for _ in range(0,model['nlay'])])`
3. `gwf.dis.botm.set_data(a)` seems to work fine with the same array, even though all "bottoms" are the same.

`gwf.dis.idomain.set_data(a)` 
Traceback (most recent call last):
  File "D:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 897, in _set_data
    def _set_data(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 893, in set_data
    def set_data(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 990, in _set_array
    def _set_array(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1072, in _set_array_by_layer
    def _set_array_by_layer(self, data, multiplier, key, preserve_record):
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1088, in _set_array_layer
    def _set_array_layer(self, data, layer, multiplier, key, preserve_record):
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1642, in store_external
    def store_external(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 3057, in _store_prep
    def _store_prep(self, layer, multiplier):
  File "D:\modelling\flopy\flopy\utils\datautil.py", line 585, in in_shape
    def in_shape(self, indexes):
TypeError: 'int' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\wesk\AppData\Local\miniforge3\envs\py39\lib\site-packages\IPython\core\interactiveshell.py", line 3342, in run_code
    async def run_code(self, code_obj, result=None, *, async_=False):
  File "<ipython-input-5-ba6d62e943bc>", line 1, in <module>
    gwf.dis.idomain.set_data(a)
  File "D:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 877, in set_data
    def set_data(self, data, multiplier=None, layer=None):
  File "D:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 897, in _set_data
    def _set_data(
flopy.mf6.mfbase.MFDataException: An error occurred in data element "idomain" model "gwf6" package "dis". The error occurred while setting data in the "_set_data" method.

**Expected behavior**
In a previous version, sending a 3d array, nlay was inferred. Using "a" from above would work with:
`gwf.dis.idomain.set_data(a)`

Similarly, `set_data()` with an nlay list of data dicts worked in the past:
`gwf.dis.idomain.set_data([{'filename': f, 'factor': 1.0, 'iprn': -1} for f in outfiles])`

With a recent pull from develop I am forced to break each `set_data()` call into a loop. Not difficult, but inconvenient and more cumbersome than having it embedded in `set_data()`:

```
for k in range(0,nlay):
            gwf.dis.idomain.set_data(a[k], layer=k)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: python 3.9, flopy 3.3.7

**Additional context**
Convenient to have nlay inferred based data passed for models with many layers, but perhaps there is a reason for the change?

**Comment by spaulins-usgs** [comment]
@wkitlasten, I may need some more information to reproduce this problem.  So far I have not been able to reproduce it using a version of the FloPy develop branch I checked out last week.  Since I do not have your simulation, I am trying to reproduce the problem by adding the following lines to some of the test cases in FloPy's autotest folder;

    model = sim.get_model(model_name)
    a = np.ones((model.dis.nlay.get_data(), model.dis.nrow.get_data(), model.dis.ncol.get_data())).astype(int)
    model.dis.idomain.set_data(a)

For the test cases I have tried so far this has worked.  Can you please supply more information on how to reproduce this?  Either the entire script you are using or show how you can reproduce the problem using one of the existing mf6 tests in autotest (autotest\test_mf6py or autotest\regression\test_mf6.py).

**Comment by wkitlasten** [comment]
Hi,

If you can point me to an example where you generate a model from scratch, rather than load an existing model, that would set me up nicely to break things! Preferably one that uses external files.

I am creating my arrays as external files, then instantiating the dis package with the following, where the filename arg points to the existing files:

```
flopy.mf6.ModflowGwfdis(gwf, nlay=nlay,
                                nrow=nrow, ncol=ncol,
                                delr=dy, delc=dx,
                                xorigin=xll, yorigin=yll,
                                top={'filename': f'{m}.dis_top.txt'},
                                botm=[{'filename': f'{m}.dis_botm_layer{_ + 1}.txt', 'factor': 1.0, 'iprn': -1}
                                      for _ in range(0, nlay)],
                                idomain=[{'filename': f'{m}.dis_idomain_layer{_ + 1}.txt', 'factor': 1.0, 'iprn': -1}
                                         for _ in range(0, nlay)])
```

The weird part is, I get the error immediately after successfully doing the same call for the botm array. (both `gwf.dis.idomain.data` and `gwf.dis.botm.data` return the `numpy.ndarrays`  expected from the external files just before this point):

```
a.shape
Out[9]: (14, 85, 80)

b.shape
Out[10]: (14, 85, 80)

gwf.dis.botm.set_data(b)
(successful)

gwf.dis.idomain.set_data(a)
Traceback (most recent call last):
  File "D:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 997, in _set_data
    storage.set_data(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 917, in set_data
    self._set_array(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1009, in _set_array
    success = self._set_array_by_layer(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1083, in _set_array_by_layer
    success = success and self._set_array_layer(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1103, in _set_array_layer
    self.store_external(
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1659, in store_external
    layer_new, multiplier = self._store_prep(layer, multiplier)
  File "D:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 3081, in _store_prep
    if not mult_ml.in_shape(layer):
  File "D:\modelling\flopy\flopy\utils\datautil.py", line 588, in in_shape
    for index, item in zip(indexes, self.list_shape):
TypeError: 'int' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\wesk\AppData\Local\miniforge3\envs\py39\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-b05136da0e72>", line 1, in <module>
    gwf.dis.idomain.set_data(a)
  File "D:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 895, in set_data
    self._set_data(data, multiplier, layer)
  File "D:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 1006, in _set_data
    raise MFDataException(
flopy.mf6.mfbase.MFDataException: An error occurred in data element "idomain" model "gwf6" package "dis". The error occurred while setting data in the "_set_data" method.
```

But if I set idomain using the loop:
```
for k in range(0,nlay):
    gwf.dis.idomain.set_data(a[k], layer=k)
```
Followed by the troublesome call, it works, suggesting something isn't getting set when the external idomain file is read (but is getting set for all the others?):
```
gwf.dis.idomain.set_data(a)
```

Sorry that's all I have. I will try to come up with a (non) working example when I get some free time.

**Comment by emorway-usgs** [comment]
Hi @wkitlasten, in case you hadn't seen [this](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_tutorial.ipynb) notebook, it demonstates external files and appears to be building the model from scratch.  Perhaps it is starting point for recreating the potential bug you're seeing.

**Comment by spaulins-usgs** [comment]
@wkitlasten, I was able to reproduce the problem using the additional information you provided.  I have a fix on this branch of flopy here:

https://github.com/scottrp/flopy/tree/array_shape_fix

Please verify that this fixes the problem for you.

**Comment by wkitlasten** [comment]
Hi Scott, this fixes the problem for me. Thanks!
