### ISSUE TITLE
"flopy.utils.binaryfile" not working with "mf2005dbl" 

### ISSUE THREAD

**Issue by mrustl** [modflowpy/flopy#181]
Using the **mf2005dbl** works running the MODFLOW model with flopy (on both Ubuntu and Windows 7) but using loading the results data with the class **flopy.utils.binaryfile** fails with the following error message (I am using the official **flopy 3.2.5 release**): 

`import` flopy.utils.binaryfile as bf`

#### Get the headfile and budget file objects
`headobj = bf.HeadFile(modelname+'.hds')`
`times = headobj.get_times()`
`cbb = bf.CellBudgetFile(modelname+'.cbc')`
Traceback (most recent call last):

  File "<ipython-input-4-bf41bc69e638>", line 8, in <module>
    `headobj = bf.HeadFile(modelname+'.hds')`

  File "C:\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\flopy\utils\binaryfile.py", line 334, in __init__
    `super(HeadFile, self).__init__(filename, precision, verbose, kwargs)`

  File "C:\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\flopy\utils\binaryfile.py", line 161, in __init__
    `super(BinaryLayerFile, self).__init__(filename, precision, verbose, kwargs)`

  File "C:\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\flopy\utils\datafile.py", line 124, in __init__
    `np.ones(self.nrow), 0)`

  File "C:\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\numpy\core\numeric.py", line 190, in ones
    `a = empty(shape, dtype, order)`

MemoryError

**Comment by langevin-usgs** [comment]
You need to tell the binary file reader that it is a double precision file:

    headobj = bf.HeadFile(modelname+'.hds', precision='double')
