### ISSUE TITLE
Add totim to title for .plot() method with binary file.

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#213]

**Comment by terrence1666** [comment]
I got some errors about plot when I was trying to implement 'tutorial 2':

Here are the errors and scripts:

> Traceback (most recent call last):
  File "L:/Python3/p2.py", line 149, in <module>
    head = headobj.get_data (totim=time)
  File "C:\Python36\lib\site-packages\flopy\utils\datafile.py", line 425, in get_data
    data = self._get_data_array(totim1)
  File "C:\Python36\lib\site-packages\flopy\utils\datafile.py", line 322, in _get_data_array
    raise Exception(msg)
Exception: totim value (101.0) not found in file...

```
import numpy as np
import flopy
import os
import shutil

workspace = os.path.join ( 't2' )

# create model directory
if os.path.exists ( workspace ):
    shutil.rmtree ( workspace )

if not os.path.exists ( workspace ):
    os.makedirs ( workspace )

# Model domain and grid definition
Lx = 1000
Ly = 1000
ztop = 0
zbot = -50
nlay = 1
nrow = 10
ncol = 10
delr = Lx / ncol
delc = Ly / nrow
delv = (ztop - zbot) / nlay
botm = np.linspace(ztop, zbot, nlay + 1)
hk = 10
vka = 10
sy = 0.1
ss = 1.e-4
laytyp = 1

# Variables for the BAS package
# Note that changes from the previous tutorial!
ibound = np.ones((nlay, nrow, ncol), dtype=np.int32)

strt = 10 * np.ones ((nlay, nrow, ncol), dtype=np.float32)

# Time step parameters
nper = 3
perlen = [1, 100, 100]
nstp = [1, 100, 100]
steady = [True, False, False]

# Flopy objects
modelname = 'tutorial2'
mf = flopy.modflow.Modflow(modelname = modelname, exe_name='mf2005', model_ws=workspace)
dis = flopy.modflow.ModflowDis (mf, nlay = nlay, nrow = nrow, ncol = ncol, delr=delr, delc=delc, nper=nper, perlen=perlen, nstp=nstp, itmuni=4, steady = steady, botm = botm[1:])
bas ```
= flopy.modflow.ModflowBas (mf, ibound = ibound, strt = strt)
lpf = flopy.modflow.ModflowLpf(mf, hk=hk, vka=vka, sy=sy, ss=ss, laytyp=laytyp, ipakcb = 100)
pcg 
```= flopy.modflow.ModflowPcg(mf)
# Output control
spd = {(0,0):['save head',
              'save budget',
              'save drawdown',
              'print head',
              'print budget']}
oc = flopy.modflow.ModflowOc(mf,stress_period_data = spd, save_head_every = 1, compact = True)

# Create the well package
# Remember to use zero-based layer, row, column indices!
pumping_rate = -100.
wel_sp1 = [ [ 0, nrow / 2 - 1, ncol / 2 - 1, 0. ] ]
wel_sp2 = [ [ 0, nrow / 2 - 1, ncol / 2 - 1, -200 ] ]
wel_sp3 = [ [ 0, nrow / 2 - 1, ncol / 2 - 1, pumping_rate] ]
stress_period_data2 = {0: wel_sp1, 1: wel_sp2, 2: wel_sp3}
wel = flopy.modflow.ModflowWel (mf, stress_period_data = stress_period_data2)



# Write the model input files
mf.write_input ()

# Run the model
success, mfoutput = mf.run_model(silent=False, pause=False )
if not success:
    raise Exception ( 'MODFLOW did not terminate normally.' )

# Imports
import matplotlib.pyplot as plt
import flopy.utils as bf

# Create the headfile and budget file objects
headobj = bf.HeadFile ( os.path.join ( workspace, modelname + '.hds'))
cbb = bf.CellBudgetFile ( os.path.join ( workspace, modelname + '.cbc' ) )
time = headobj.get_times()

# Setup contour parameters
levels = np.linspace ( 0, 10, 11 )
extent = (delr / 2, Lx - delr / 2, delc / 2, Ly - delc / 2)
print ( 'Levels: ', levels )
print ( 'Extent: ', extent )

# Well point
wpt = ((float(ncol/2)-0.5)*delr, (float(nrow/2-1)+0.5)*delc)


# Make the plots
mytimes = [1.0, 101.0, 201.0]
for iplot, time in enumerate(mytimes):
    print ('*****Processing time: ', time)
    head = headobj.get_data (totim=time)
    print ('Head statistics')
    print ('  min: ', head.min())
    print ('  max: ', head.max())
    print ('  std: ', head.std())
    #Create the plot
    #plt.subplot(1, len(mytimes), iplot + 1, aspect='equal')
    plt.subplot(1, 1, 1, aspect='equal')
    plt.title('stress period ' + str(iplot + 1))
    plt.imshow(head[0, :, :], extent=extent, cmap='BrBG', vmin=0., vmax=10.)
    plt.colorbar()
    CS = plt.contour(np.flipud(head[0, :, :]), levels=levels, extent=extent,
                     zorder=10)
    plt.clabel(CS, inline=1, fontsize=10, fmt='%1.1f', zorder=11)
    mfc = 'None'
    if (iplot+1) == len(mytimes):
        mfc='black'
    plt.plot(wpt[0], wpt[1], lw=0, marker='o', markersize=8,
                markeredgewidth=0.5, markeredgecolor='black', 
                markerfacecolor=mfc, zorder=9)
    plt.text(wpt[0]+25, wpt[1]-25, 'well', size=12, zorder=12)
    plt.show()
plt.show()

# Plot the head versus time
idx = (0,(nrow/2 - 1),  (ncol/2 - 1))
ts = headobj.get_ts (idx)
plt.subplot ( 1, 1, 1 )
ttl = 'Head at cell ({0},{1},{2})'.format ( idx[ 0 ] + 1, idx[ 1 ] + 1, idx[ 2 ] + 1 )
plt.title ( ttl )
plt.xlabel ( 'time' )
plt.ylabel ( 'head' )
plt.plot (ts)
plt.show ()

```
When I open the list file, it shows "no output control in stress period 2 and 3". I want to know is there any problems with the scripts or something else? P.S. Now I am using the flopy version 3.2.8. Thanks for your attention. 
[tutorial2_list.txt](https://github.com/modflowpy/flopy/files/1569646/tutorial2_list.txt)

**Comment by jtwhite79** [comment]
I think you have to explicit for the OC ``stress_period_data`` arg - if you add the other stress periods to the OC constructor, then 101.0 should be in the OC times...

**Comment by terrence1666** [comment]
Thanks for your reply. It helps me a lot to solve my problem.
