### ISSUE TITLE
flopy.modflow.mfdisu Module

### ISSUE THREAD

**Issue by hjia1005** [modflowpy/flopy#258]
Hi, I am using the Biscayne data (created from Gridgen) to learn how to use modflow-usg. Trying to create input packages in flopy. The first package i am creating is DISU.

`disu=flopy.modflow.mfdisu.ModflowDisU(mfusg, nodes=94696, nlay=1, njag=492644, ivsd=0, nper=1, itmuni=4, lenuni=2, idsymrd=0, laycbd=0, nodelay=None, top=array_top[0:], bot=array_bot[0:], area=array_area[0:], iac=array_iac[0:], ja=array_ja[0:], ivc=ivc, cl1=array_cl1[0:], cl2=array_cl2[0:], cl12=None, fahl=array_fahl[0:], perlen=1, nstp=1, tsmult=1, steady=True, extension='disu', unitnumber=40, filenames=None, start_datetime='1/1/1970')`

All the array data are imported from the text files created by Gridgen using the following code (take array_iac as example):

```
fo=open(r'C:\...\Biscayne\Files_Flopy\grid02qtg.iac.dat',"r")
array_iac=fo.read().split()
array_iac=[int(x) for x in array_iac]
```

But I receive error message below.

```
Traceback (most recent call last):
  File "<pyshell#58>", line 1, in <module>
    disu=flopy.modflow.mfdisu.ModflowDisU(mfusg, nodes=94696, nlay=1, njag=492644, ivsd=0, nper=1, itmuni=4, lenuni=2, idsymrd=0, laycbd=0, nodelay=None, top=array_top[0:], bot=array_bot[0:], area=array_area[0:], iac=array_iac[0:], ja=array_ja[0:], ivc=ivc, cl1=array_cl1[0:], cl2=array_cl2[0:], cl12=None, fahl=array_fahl[0:], perlen=1, nstp=1, tsmult=1, steady=True, extension='disu', unitnumber=40, filenames=None, start_datetime='1/1/1970')
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\modflow\mfdisu.py", line 270, in __init__
    locat=self.unit_number[0])
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\utils\util_array.py", line 550, in __init__
    self.util_2ds = self.build_2d_instances()
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\utils\util_array.py", line 775, in build_2d_instances
    ' != to shape[0]:' + str(self.shape[0])
AssertionError: length of 3d enumerable:94696 != to shape[0]:1
```

I am still new to python so cannot figure out what's the problem. I can make sure that all the arrays are correct. Please help.

Regards

**Comment by langevin-usgs** [comment]
Instead of reading the array using your syntax, try using the read1d function in flopy.utils.util_array with something like this (note that syntax may not be exact):

```
nodes = ?
fname = r'C:\...\Biscayne\Files_Flopy\grid02qtg.iac.dat'
iac = np.empty((nodes), dtype=np.int)
iac = flopy.utils.util_array.read1d(fname, iac)
```

We use the read1d array function quite a bit in flopy as a way to read in arrays from a text file.

**Comment by langevin-usgs** [comment]
It takes the file handle instead:

```
        # iac
        iac = np.empty((nodes), dtype=np.int)
        fname =  'qtg.iac.dat'
        f = open(fname, 'r')
        iac = read1d(f, iac)
        f.close()

```

**Comment by hjia1005** [comment]
May I ask what is "nodes"?
Number of nodes in the usg model?

**Comment by hjia1005** [comment]
or it is the size of the iac array?

**Comment by langevin-usgs** [comment]
Yes, nodes is the number of nodes in the model.  iac is of size, nodes.

**Comment by hjia1005** [comment]
because all those array have different size. so I need find out the size of each first then create the empty array first?

**Comment by langevin-usgs** [comment]
Here is the code from gridgen.py that does what you are trying to do.

```
    def get_disu(self, model, nper=1, perlen=1, nstp=1, tsmult=1, steady=True,
                 itmuni=4, lenuni=2):

        # nodes, nlay, ivsd, itmuni, lenuni, idsymrd, laycbd
        fname = os.path.join(self.model_ws, 'qtg.nod')
        f = open(fname, 'r')
        line = f.readline()
        ll = line.strip().split()
        nodes = int(ll.pop(0))
        f.close()
        nlay = self.dis.nlay
        ivsd = 0
        idsymrd = 0
        laycbd = 0

        # Save nodes
        self.nodes = nodes

        # nodelay
        nodelay = np.empty((nlay), dtype=np.int)
        fname = os.path.join(self.model_ws, 'qtg.nodesperlay.dat')
        f = open(fname, 'r')
        nodelay = read1d(f, nodelay)
        f.close()

        # top
        top = [0] * nlay
        for k in range(nlay):
            fname = os.path.join(self.model_ws,
                                 'quadtreegrid.top{}.dat'.format(k + 1))
            f = open(fname, 'r')
            tpk = np.empty((nodelay[k]), dtype=np.float32)
            tpk = read1d(f, tpk)
            f.close()
            if tpk.min() == tpk.max():
                tpk = tpk.min()
            else:
                tpk = Util2d(model, (1, nodelay[k]), np.float32,
                             np.reshape(tpk, (1, nodelay[k])),
                             name='top {}'.format(k + 1))
            top[k] = tpk

        # bot
        bot = [0] * nlay
        for k in range(nlay):
            fname = os.path.join(self.model_ws,
                                 'quadtreegrid.bot{}.dat'.format(k + 1))
            f = open(fname, 'r')
            btk = np.empty((nodelay[k]), dtype=np.float32)
            btk = read1d(f, btk)
            f.close()
            if btk.min() == btk.max():
                btk = btk.min()
            else:
                btk = Util2d(model, (1, nodelay[k]), np.float32,
                             np.reshape(btk, (1, nodelay[k])),
                             name='bot {}'.format(k + 1))
            bot[k] = btk

        # area
        area = [0] * nlay
        fname = os.path.join(self.model_ws, 'qtg.area.dat')
        f = open(fname, 'r')
        anodes = np.empty((nodes), dtype=np.float32)
        anodes = read1d(f, anodes)
        f.close()
        istart = 0
        for k in range(nlay):
            istop = istart + nodelay[k]
            ark = anodes[istart: istop]
            if ark.min() == ark.max():
                ark = ark.min()
            else:
                ark = Util2d(model, (1, nodelay[k]), np.float32,
                             np.reshape(ark, (1, nodelay[k])),
                             name='area layer {}'.format(k + 1))
            area[k] = ark
            istart = istop

        # iac
        iac = np.empty((nodes), dtype=np.int)
        fname = os.path.join(self.model_ws, 'qtg.iac.dat')
        f = open(fname, 'r')
        iac = read1d(f, iac)
        f.close()

        # Calculate njag and save as nja to self
        njag = iac.sum()
        self.nja = njag

        # ja
        ja = np.empty((njag), dtype=np.int)
        fname = os.path.join(self.model_ws, 'qtg.ja.dat')
        f = open(fname, 'r')
        ja = read1d(f, ja)
        f.close()

        # ivc
        fldr = np.empty((njag), dtype=np.int)
        fname = os.path.join(self.model_ws, 'qtg.fldr.dat')
        f = open(fname, 'r')
        fldr = read1d(f, fldr)
        ivc = np.where(abs(fldr) == 3, 1, 0)
        f.close()

        cl1 = None
        cl2 = None
        # cl12
        cl12 = np.empty((njag), dtype=np.float32)
        fname = os.path.join(self.model_ws, 'qtg.c1.dat')
        f = open(fname, 'r')
        cl12 = read1d(f, cl12)
        f.close()

        # fahl
        fahl = np.empty((njag), dtype=np.float32)
        fname = os.path.join(self.model_ws, 'qtg.fahl.dat')
        f = open(fname, 'r')
        fahl = read1d(f, fahl)
        f.close()

        # create dis object instance
        disu = ModflowDisU(model, nodes=nodes, nlay=nlay, njag=njag, ivsd=ivsd,
                           nper=nper, itmuni=itmuni, lenuni=lenuni,
                           idsymrd=idsymrd, laycbd=laycbd, nodelay=nodelay,
                           top=top, bot=bot, area=area, iac=iac, ja=ja,
                           ivc=ivc, cl1=cl1, cl2=cl2, cl12=cl12, fahl=fahl,
                           perlen=perlen, nstp=nstp, tsmult=tsmult,
                           steady=steady)

        # return dis object instance
        return disu


```

**Comment by hjia1005** [comment]
Thanks a lot, will read through and try to understand!

Kind regards
hjia

**Comment by hjia1005** [comment]
Hi I tried to run but the following error occurred.
```
>>> iac = flopy.utils.util_array.read1d(fname, iac)

Traceback (most recent call last):
  File "<pyshell#66>", line 1, in <module>
    iac = flopy.utils.util_array.read1d(fname, iac)
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\utils\util_array.py", line 411, in read1d
    line = f.readline()
AttributeError: 'str' object has no attribute 'readline'
```

**Comment by hjia1005** [comment]
Tried many times, flopy.utils.util_array.read1d  really doesn't work for me :(

**Comment by mbakker7** [comment]
I think your fname must be a handle to a file rather than the name of the
file. Have you tried that?

**Comment by hjia1005** [comment]
Thank you so much!!! It works now. Now can try the DISU class again.

**Comment by hjia1005** [comment]
Hi Langevin and Bakker, 

The Biscayne is too complicated to run as an example. It takes too long to create the packages.

I used Gridgen created a small model (with only 129 nodes and 685 connections), the DISU package is finally passed. but now I got problem with the BAS package.

```
ibound = np.empty((nodes), dtype=np.int)
fname = r'C:\temp\ModelExample\Flopy Files\bound.txt'
f = open(fname, 'r')
ibound = flopy.utils.util_array.read1d(f, ibound)
f.close()

strt = np.empty((nodes), dtype=np.float32)
fname = r'C:\temp\ModelExample\Flopy Files\strt.txt'
f = open(fname, 'r')
strt = flopy.utils.util_array.read1d(f, strt)
f.close()
```
`bas = flopy.modflow.ModflowBas(mf, ibound=ibound, strt=strt)`
 
I got the following error message.

```
Traceback (most recent call last):
  File "C:/temp/ModelExample/Flopy Files/CreatDisU_test", line 68, in <module>
    bas = flopy.modflow.ModflowBas(mf, ibound=ibound, strt=strt)
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\modflow\mfbas.py", line 123, in __init__
    name='ibound', locat=self.unit_number[0])
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\utils\util_array.py", line 550, in __init__
    self.util_2ds = self.build_2d_instances()
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\flopy\utils\util_array.py", line 775, in build_2d_instances
    ' != to shape[0]:' + str(self.shape[0])
AssertionError: length of 3d enumerable:129 != to shape[0]:1
```

I checked that the arrays (ibound and strt) are fine - both are 1 dimension array with 129 elements.
It seems flopy requests a 3D array other than a 1D array. But this is for usg model. Is this the right class to use for usg models? I feel that I missed something here. but don't know what it is. I am really new to python so struggle to read the source code.

Could you please help?

Regards
hjia
