### ISSUE TITLE
import fails in python 3.4.4

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#262]
after installing the most recent develop branch, i get this on import
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/github/flopy/autotest/t001_test.py", line 12, in <module>
    import flopy
  File "E:\ATLData\software\py34\lib\site-packages\flopy-3.2.6-py3.4.egg\flopy\__init__.py", line 37, in <module>
    from . import mf6
ImportError: cannot import name 'mf6'
```

**Comment by langevin-usgs** [comment]
Well that is certainly related to something that I just committed.  I'll have to look at it tonight or tomorrow.

**Comment by langevin-usgs** [comment]
Seems strange.  It looks like tests are passing.

**Comment by aleaf** [comment]
here's a link to the python distribution I was using. 
<ftp://ftpint.usgs.gov/pub/er/wi/middleton/Leaf/py34.zip>
It is from python.org.
