### ISSUE TITLE
Fail to install flopy with python3

### ISSUE THREAD

**Issue by chiehhanl** [modflowpy/flopy#383]
Hi,
I successfully installed and run flopy with python2. But there is an issue when I tried to install flopy for python3. it shows

Collecting flopy
  Using cached https://files.pythonhosted.org/packages/f5/a6/806b0930db62718e1cc9851c65efd560446eba84639eb831c3b0503e02cc/flopy-3.2.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7n/prspbnrx7kb30pr35y77qfp40000gn/T/pip-install-ijngwt6p/flopy/setup.py", line 7, in <module>
        from flopy import __version__, __name__, __author__
      File "/private/var/folders/7n/prspbnrx7kb30pr35y77qfp40000gn/T/pip-install-ijngwt6p/flopy/flopy/__init__.py", line 28, in <module>
        from . import modflow
      File "/private/var/folders/7n/prspbnrx7kb30pr35y77qfp40000gn/T/pip-install-ijngwt6p/flopy/flopy/modflow/__init__.py", line 1, in <module>
        from .mf import Modflow
      File "/private/var/folders/7n/prspbnrx7kb30pr35y77qfp40000gn/T/pip-install-ijngwt6p/flopy/flopy/modflow/mf.py", line 11, in <module>
        from ..mbase import BaseModel
      File "/private/var/folders/7n/prspbnrx7kb30pr35y77qfp40000gn/T/pip-install-ijngwt6p/flopy/flopy/mbase.py", line 1311
        async=False, cargs=None):
            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7n/prspbnrx7kb30pr35y77qfp40000gn/T/pip-install-ijngwt6p/flopy/

( I've re-installed python3 and pip to make they're not broken. )
Thank you for your help!

**Comment by jtwhite79** [comment]
I've seen this too -  I think``async`` has become a keyword in latest [python 3](https://www.python.org/dev/peps/pep-0492/). This should be patched in the ``develop`` branch. Can you try to pip install from the develop branch directly to see if it is fixed for you?:
``pip install git+https://github.com/modflowpy/flopy.git@develop``

**Comment by chiehhanl** [comment]
@jtwhite79 The problem is fixed if install with the development version. (Maybe need a footnote to specify the correct python 3 version in installation guide before the new flopy version release?) Thanks for your assistance!

**Comment by ashu160584** [comment]
I have the same issue I guess!
Could install only pip3 and pip3.7

sh-3.2# pip3 install https://github.com/modflowpy/flopy/zipball/develop
Collecting https://github.com/modflowpy/flopy/zipball/develop
  Downloading https://github.com/modflowpy/flopy/zipball/develop
     \ 198.8MB 10.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-qbs5bznp/setup.py", line 7, in <module>
        from flopy import __version__, __name__, __author__
      File "/private/tmp/pip-req-build-qbs5bznp/flopy/__init__.py", line 30, in <module>
        from . import modflow
      File "/private/tmp/pip-req-build-qbs5bznp/flopy/modflow/__init__.py", line 1, in <module>
        from .mf import Modflow
      File "/private/tmp/pip-req-build-qbs5bznp/flopy/modflow/mf.py", line 10, in <module>
        from ..mbase import BaseModel
      File "/private/tmp/pip-req-build-qbs5bznp/flopy/mbase.py", line 21, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-qbs5bznp/
sh-3.2# pip3.7 install https://github.com/modflowpy/flopy/zipball/develop
Collecting https://github.com/modflowpy/flopy/zipball/develop
  Downloading https://github.com/modflowpy/flopy/zipball/develop
     | 198.7MB 8.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-s8k4fmo1/setup.py", line 7, in <module>
        from flopy import __version__, __name__, __author__
      File "/private/tmp/pip-req-build-s8k4fmo1/flopy/__init__.py", line 30, in <module>
        from . import modflow
      File "/private/tmp/pip-req-build-s8k4fmo1/flopy/modflow/__init__.py", line 1, in <module>
        from .mf import Modflow
      File "/private/tmp/pip-req-build-s8k4fmo1/flopy/modflow/mf.py", line 10, in <module>
        from ..mbase import BaseModel
      File "/private/tmp/pip-req-build-s8k4fmo1/flopy/mbase.py", line 21, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-s8k4fmo1/
sh-3.2# which python
/usr/bin/python
sh-3.2# python --version
Python 2.7.10
sh-3.2# python3 --version
Python 3.7.0
sh-3.2#

**Comment by szipper** [comment]
Just wanted to +1 that we had the same `async` issue here, and installing the development version worked like a charm. Thanks!
