### ISSUE TITLE
issue with the Spatial Reference demo

### ISSUE THREAD

**Issue by Weiwei-Mao** [modflowpy/flopy#446]
When I tried to repeat the Spatial Reference demo, an error happened when I execute the 14 row code, which wrote the "sr" to shapefile. I tried under Windows and Ubuntu, the error is same. The IDE I used is anaconda.

The error is as follows,

sr.write_shapefile(os.path.join(outpath, 'grid.shp'))
Traceback (most recent call last):

  File "<ipython-input-3-a52918953856>", line 1, in <module>
    sr.write_shapefile(os.path.join(outpath, 'grid.shp'))

  File "C:\Anaconda3\lib\site-packages\flopy\utils\reference.py", line 914, in write_shapefile
    epsg=epsg, prj=prj)

  File "C:\Anaconda3\lib\site-packages\flopy\export\shapefile_utils.py", line 115, in write_grid_shapefile2
    w = sf.Writer(5)  # polygon

  File "C:\Anaconda3\lib\site-packages\shapefile.py", line 1017, in __init__
    self.shp = self.__getFileObj(os.path.splitext(target)[0] + '.shp')

  File "C:\Anaconda3\lib\ntpath.py", line 202, in splitext
    p = os.fspath(p)

TypeError: expected str, bytes or os.PathLike object, not int

**Comment by juancastilla** [comment]
The problem persists in the develop branch. For the moment, this can be resolved by pinning Flopy to an older version of pyshp — `conda install flopy pyshp=1.2.12` solved the problem for me

**Comment by langevin-usgs** [comment]
This is the pyshp 1.x / 2.x issue.  I think it should be fixed now.
