### ISSUE TITLE
Precision could not be determined for MT3D001.UCN file SEAWAT

### ISSUE THREAD

**Issue by 1DChristopher** [modflowpy/flopy#555]
I created a SEAWAT model packages with Flopy on my Mac. The model runs fine and gives after 5 minutes the messages that the model is successively finished. However when I try to open the MT3D001.UCN file I get this error:

```
ucnobj = bf.UcnFile('MT3D001.UCN')
Error. Precision could not be determined for MT3D001.UCN
Traceback (most recent call last):

  File "<ipython-input-40-be1aa6e58989>", line 1, in <module>
    ucnobj = bf.UcnFile('MT3D001.UCN')
```
Also when I try to open the .hds file I get this error.

Now is the odd thing that on a Windows PC where the model works also fine and the files can be read.

Is someone familiar with these kind of problems? I write my model in Spyder 3.3.2, Python version installed is 3.7.0 and Flopy version 3.2.10. On a 64 bit system (OS).

**Comment by langevin-usgs** [comment]
Where did you get the mac version of SEAWAT?  You should try the one here if you haven't already: https://github.com/MODFLOW-USGS/executables

**Comment by 1DChristopher** [comment]
Hi Christian Langevin,
Thanks for your reply, I found out that the above problem was solved by defining the precision (set to double).
The model still runs fine but when I try to open the .UCN or .hds file it gives me the following error:
```

  File "<ipython-input-3-fe4f4ed37a0d>", line 1, in <module>
    runfile('/Users/User/Desktop/swt_model.py', wdir='/Users/User/Desktop')

  File "/Users/User/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/Users/User/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/User/Desktop/swt_model.py", line 431, in <module>
    headobj = bf.HeadFile(r'swt_model_0805.hds',precision='double')

  File "/Users/User/anaconda3/lib/python3.7/site-packages/flopy/utils/binaryfile.py", line 445, in __init__
    super(HeadFile, self).__init__(filename, precision, verbose, kwargs)

  File "/Users/User/anaconda3/lib/python3.7/site-packages/flopy/utils/binaryfile.py", line 246, in __init__
    kwargs)

  File "/Users/User/anaconda3/lib/python3.7/site-packages/flopy/utils/datafile.py", line 127, in __init__
    self._build_index()

  File "/Users/User/anaconda3/lib/python3.7/site-packages/flopy/utils/binaryfile.py", line 269, in _build_index
    header = self._get_header()

  File "/Users/User/anaconda3/lib/python3.7/site-packages/flopy/utils/binaryfile.py", line 323, in _get_header
    return header[0]

IndexError: index 0 is out of bounds for axis 0 with size 0
```
I deleted the old executable and used from your link the swtv4 file.

Thanks for your help! (this problem drives me crazy)

Cheers,
Christopher

**Comment by langevin-usgs** [comment]
I'm not sure what to tell you.  The SEAWAT runs have always worked fine for me on mac and windows, and I do not have to set the precision.  I assume that you've seen this: https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_SEAWAT_henry_problem.ipynb.

I'm guessing that you have a simple error somewhere in your script.

**Comment by 1DChristopher** [comment]
Okay, when running your example I found out that I was still running the old executable.
Now the .hds file is read correctly. 

For the .UCN file I still get the same error but I guess your right and that is has to do with a simple input error so I will close the issue. Thanks again for your input.
