### ISSUE TITLE
issue with vertexgrid.py

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#825]
I am trying to plot the voronoi grid of a model and I am using the command:

`sim.plot(filename_base=workspace + '\\' + name, file_extension='png')`

Please note that sim was defined just with the grid of one layer only and I have not assigned any material property.

The command above returns an error with the module vertexgrid.py:
`Traceback (most recent call last):
  File "H:/scripts/python3.6/modflow/triangulation_feflow.py", line 98, in <module>
    sim.plot(filename_base=workspace + '\\' + name, file_extension='png')
  File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\modflow\mfsimulation.py", line 1768, in plot
    **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\flopy\plot\plotutil.py", line 385, in _plot_simulation_helper
    **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\flopy\plot\plotutil.py", line 460, in _plot_model_helper
    model_name=defaults['model_name'])
  File "C:\Program Files\Python36\lib\site-packages\flopy\plot\plotutil.py", line 631, in _plot_package_helper
    colorbar=True))
  File "C:\Program Files\Python36\lib\site-packages\flopy\plot\plotutil.py", line 991, in _plot_util3d_helper
    **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\flopy\plot\plotutil.py", line 1262, in _plot_array_helper
    ax=axes[idx], **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\flopy\plot\map.py", line 160, in plot_array
    xgrid = np.array(self.mg.xvertices)
  File "C:\Program Files\Python36\lib\site-packages\flopy\discretization\grid.py", line 310, in xvertices
    return self.xyzvertices[0]
  File "C:\Program Files\Python36\lib\site-packages\flopy\discretization\vertexgrid.py", line 141, in xyzvertices
    self._build_grid_geometry_info()
  File "C:\Program Files\Python36\lib\site-packages\flopy\discretization\vertexgrid.py", line 252, in _build_grid_geometry_info
    vert_number.append(int(i))
TypeError: only size-1 arrays can be converted to Python scalars`

However, everything works fine if I modify the line 250 of "vertexgrid.py":

`            for i in cell2d[4:]:`

with:

`            for i in cell2d[4]:`

Kind Regards
Giovanni Firmani

**Comment by giovannifi** [comment]
I would like to remove this as it is not an issue.
