### ISSUE TITLE
Contours for horizontal unstructured models: problem with grid definition for PlotMapView

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#859]
I run a steady state unstructured model and I would like to plot the head contours of a layer. I use the following commands:

`# load the model`
`name = 'my_model'`
`workspace = 'my_path'`
`sim = flopy.mf6.MFSimulation.load(sim_name=name, exe_name=path_exe, sim_ws=workspace)`
`gwf = sim.get_model(name)`
`disv = gwf.get_package('DISV')`
`# load the HDS file`
`headfile = name + '.hds'`
`hds = bf.HeadFile(workspace + '\\' + headfile)`
`h = hds.get_data()`
`fig = plt.figure(figsize=(10, 10))`
`ax = fig.add_subplot(1, 1, 1, aspect='equal')`
`modelmap = flopy.plot.PlotMapView(model=sim, modelgrid=disv, ax=ax)`
`linecollection = modelmap.plot_grid()`
`contours = modelmap.contour_array(h[5])`
`plt.show()`

the command `disv = gwf.get_package('DISV')` gives me the following message:

`Unable to get repr for <class 'flopy.mf6.modflow.mfgwfdisv.ModflowGwfdisv'>`

but the script does not stop and it seems that the grid is loaded. I manage to get that message only when I debug the script and please note that I did not get the same message when I loaded structured grids in the past.
In the end the script fails when it reaches the command with PlotMapView:

`Traceback (most recent call last):`
`  File "H:/scripts/python3.6/modflow/post_process_mf.py", line XX, in <module>`
`    modelmap = flopy.plot.PlotMapView(model=sim, modelgrid=disv, ax=ax)`
  ```
File "C:\Program Files\Python36\lib\site-packages\flopy\plot\map.py", line 59, in __init__
    self.mg = model.modelgrid
```
  `File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\modflow\mfsimulation.py", line 532, in __getattr__`
`    raise AttributeError(item)`
`AttributeError: modelgrid`

If I run the second part of the code (after the comment "load hds file) immediately after the simulation (i.e. I do not have to load the model and the disv package), everything works fine.

I am not sure what I am doing wrong or if this is an issue with the "get_package" method.

**Comment by giovannifi** [comment]
I managed to get it working with the command:

`modelmap = flopy.plot.PlotMapView(model=gwf, ax=ax)`
