### ISSUE TITLE
export method for the disu, disv, npf etc. does not create .nc files

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#873]
I defined a model grid using voronoi cells. I built the model using the DISV package in MF6.
When I try to use the following commands in python:

`gwf.disv.export(workspace + '\\' + 'disv_mf6.nc')`
`gwf.npf.export(workspace + '\\' + 'npf_mf6.nc')`

I get the following error

`Traceback (most recent call last):`
```
  File "H:/scripts/python3.6/modflow/post_process_mf.py", line 78, in <module>
    gwf.npf.export(workspace + '\\' + 'npf_mf6.nc')
```
```
  File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\mfpackage.py", line 1762, in export
    return export.utils.package_export(f, self, **kwargs)
```
`  File "C:\Program Files\Python36\lib\site-packages\flopy\export\utils.py", line 468, in package_export`
`    f = NetCdf(f, pak.parent, **kwargs)`
```
  File "C:\Program Files\Python36\lib\site-packages\flopy\export\netcdf.py", line 175, in __init__
    self.model_grid.grid_type))
```
`Exception: Grid type vertex not supported.`

everything works fine if I try to export shape files.
Thanks in advance

**Comment by langevin-usgs** [comment]
The last we checked there wasn't a stable standard for writing netcdf files for unstructured grids.  Maybe this has changed by now, but it has been low on our priority list.  Is there a reason you need netcdf files for your model?

**Comment by giovannifi** [comment]
No worries. I have no urgencies. Just wanted to notify the bug if it is a
bug.
It would be nice to have the option. I wanted to load the model with
paraview and create some nice 3d pictures for reporting purposes. I also
wanted to produce some cross sections. I managed to write a script code for
the last one but it is not really efficient.

**Comment by langevin-usgs** [comment]
If you want to make plots with Paraview, then VTK is probably a better option.  You should be able to export a DISV model to VTK output files.

**Comment by giovannifi** [comment]
I had the impression that the vtk commands/methods work only for the
structured grids. I have not figured out how to use them for an
unstructured grid with voronoi cells. If you say that it is possible, I
will investigate more. Thanks a lot for that.

**Comment by langevin-usgs** [comment]
Sorry, you're right.  I don't think we have VTK support yet for unstructured grids.

**Comment by giovannifi** [comment]
I manged to create a function to create the VTK for unstructured grids using the module vtk that has to be installed in python with the command:

`pip install vtk`

The code can be found here: https://www.dropbox.com/s/n2p9b0w7lef038f/vtk_grid.zip?dl=0

My script generates the VTK file for a horizontal unstructured grid built for MF6 with the DISV package. It also add the hydraulic conductivity to the vtk file as a cell scalar.
The key function of my script is called MakePrism, that, I would reckon, could also work for a fully unstructured grid provided that "Faces" and "p_list" will be defined accordingly.

- “P_list” is a list of the coordinates of all the vertices 
- “Faces” is a list of lists whose length is equal to the number of cells. For each cell you have to define a list of vertices for each face of the cell

I hope this could help anyone.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs is this something DJ could work on?

**Comment by etiennebresciani** [comment]
I would be interested in principle, but time is indeed an issue here... I would have a hard time justifying it as I am not working with unstructured grids at this stage.

Just some thoughts: it may not be a bad idea to indeed use the genuine vtk python module, as @giovannifi did. It could be used throughout (i.e., even for structured grids). This would add a dependency, but on the other hand it would reduce the amount of code to maintain.

**Comment by marcowhites** [comment]
Hi, any update on this topic? I'd like to export a DISU model outputs into vtk format

**Comment by jlarsen-usgs** [comment]
@marcowhites, @giovannifi 

I've started working on updating/rewriting the VTK code to be able to export DISV and DISU models. @giovannifi thanks for sharing your code, I've been looking through it and will probably adapt some if it for the flopy VTK module.

**Comment by marcowhites** [comment]
@jlarsen-usgs 
Thanks! For now, since I am using Flopy and Gridgen, I am using a piece of code to paste the modelling results on the VTK file created by Gridgen when I generate the DISU grid. It's clearly a rough patch, but it works

**Comment by jlarsen-usgs** [comment]
@giovannifi @marcowhites @langevin-usgs @jdhughes-usgs @khm293 @NigelKinney @Matt-Webb1

Hi everyone, 

I've been working on the new VTK class using the python vtk library to export DIS, DISV, DISU grids, HFB planes, and MODPATH pathline points and timeseries. After inspecting the existing flopy Vtk code, there are a few options that I wanted to ask the community if 1) they are being used, 2) should we continue supporting them or remove them. 

The options are:

- `point_scalars` : outputs array values at cell vertices, default is False
- `true2d`: default is False, I'm leaning toward removing (not adding) this option in the new Vtk class.
- `smooth`: creates smooth layer elevations, default is False (also leaning toward removing this option).

Please chime in if you have an opinion about these parameters. And if you're using any of these options, what added benefit do these parameters provide.

Thank you!

issue #1070 
issue #1127
issue #1114

**Comment by Matt-Webb1** [comment]
HI Joshua,

Thanks for keeping me in the loop with this. I have used the point_scalars
fairly often (if I recall correctly it is required for certain filters to
display properly in ParaView), and almost always use the smooth option
since it is much better for presentation visualisations. haven't used the
true2d option yet.

Good to hear about the work on the pathlines/particles/HFBs. I have managed
to get a working example for each of these, but my code is scruffy (and for
the particles is partially written in Python and partially in VBA) so
wouldn't recommend including any of it in FloPy in any way! I doubt my
takes on it are particularly useful, but just in case, here's a high-level
overview of what I found:

   - The HFB was easy enough (just grabbing the vertex coordinates with
   existing functions in FloPy and writing those to a VTU file).
   - The particles were a bit more complicated but the trick for me was to
   use the time-series output format from MODPATH 6 since the particle
   locations have to be defined at *all *timesteps for *all* particles in
   the vtu file (to avoid all sorts of rendering errors in ParaView when you
   try to use pathlines filters to draw the entire particle trace). For that I
   had to insert extra rows of data to represent the time before a particle
   was released, and also for the time after it was captured, but once I had
   those the x/y/z/time data was easy to convert to vtu.

Cheers,

Matt
