### ISSUE TITLE
install fails if numpy is not yet installed.

### ISSUE THREAD

**Issue by ritchie46** [modflowpy/flopy#892]
See the following example in a clean docker image:

```
docker run -it --rm python:3.7-slim-stretch bash
root@0df35496ca06:/# pip install flopy
Collecting flopy
  Downloading flopy-3.3.0.zip (1.0 MB)
     |████████████████████████████████| 1.0 MB 3.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jr9tzpz2/flopy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jr9tzpz2/flopy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n4o_yoja
         cwd: /tmp/pip-install-jr9tzpz2/flopy/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jr9tzpz2/flopy/setup.py", line 5, in <module>
        from flopy import __version__, __name__, __author__
      File "/tmp/pip-install-jr9tzpz2/flopy/flopy/__init__.py", line 33, in <module>
        from . import modflow
      File "/tmp/pip-install-jr9tzpz2/flopy/flopy/modflow/__init__.py", line 1, in <module>
        from .mf import Modflow
      File "/tmp/pip-install-jr9tzpz2/flopy/flopy/modflow/mf.py", line 10, in <module>
        from ..mbase import BaseModel
      File "/tmp/pip-install-jr9tzpz2/flopy/flopy/mbase.py", line 21, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@0df35496ca06:/# 
```

**Comment by langevin-usgs** [comment]
This is stated in the installation instructions: FloPy requires NumPy 1.9 (or higher).

**Comment by ritchie46** [comment]
But is it required for the installation process? If so couldn't it be added as a build requirement in `pyproject.toml`. If it isn't required a simple 

```
try:
   import numpy
except ImportError:
   pass
```

could solve this. Numpy is added in the `setup.py` under `install_requires` so will be installed if it is not.
