### ISSUE TITLE
Error in reading drawdown file 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#93]
Hi Guys, 
Does the current release support drawdown file reading? I can read binary head files, but with drawdown, I received the following message. I have tried this on different models. 
"Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "C:\Project\Arrow_Project\t4_NSMC_60_models\NSMC_PRE_NO_CSG\test_ddn.py", line 7, in <module>
    hdobj = fp.utils.HeadFile('NSMC_PRE_NO_CSG.ddn',precision='single')
  File "C:\Anaconda2\lib\site-packages\flopy\utils\binaryfile.py", line 325, in __init__
    super(HeadFile, self).__init__(filename, precision, verbose, kwargs)
  File "C:\Anaconda2\lib\site-packages\flopy\utils\binaryfile.py", line 160, in __init__
    super(BinaryLayerFile, self).__init__(filename, precision, verbose, kwargs)
  File "C:\Anaconda2\lib\site-packages\flopy\utils\datafile.py", line 118, in __init__
    self._build_index()
  File "C:\Anaconda2\lib\site-packages\flopy\utils\binaryfile.py", line 178, in _build_index
    header = self._get_header()
**  File "C:\Anaconda2\lib\site-packages\flopy\utils\binaryfile.py", line 212, in _get_header
    return header[0]
IndexError: index 0 is out of bounds for axis 0 with size 0"**

The code I use is below. 
#%% load head data
hdobj = fp.utils.HeadFile('NSMC_PRE_NO_CSG.ddn',precision='single')
# layer 1
arr_0 = hdobj.get_alldata(mflay=0)

**Comment by jtwhite79** [comment]
try:
``hdobj = fp.utils.HeadFile('NSMC_PRE_NO_CSG.ddn',precision='single', text="drawdown")``

**Comment by flydream0428** [comment]
Thanks Jeremy :+1:
